behaviors:
  Player:
    trainer_type: ppo
    max_steps: 50000000
    hyperparameters:
      batch_size: 256
      buffer_size: 102400
      learning_rate: 0.0003
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      memory:
        sequence_length: 10
        memory_size: 32
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
torch_settings:
  device: cuda
engine_settings:
  no_graphics: true
  time_scale: 20
