behaviors:
  Adaptivity:
    trainer_type: sac
    max_steps: 50000000
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 1000000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.05
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      memory:
        sequence_length: 10
        memory_size: 32
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
torch_settings:
  device: cuda
engine_settings:
  no_graphics: true
  time_scale: 20
